### PR TITLE
chore: add dmn-js guide

### PR DESCRIPTION
**Pull request by MaxTru**
Related to https://github.com/bpmn-io/dmn-js/issues/641

### CODE REVIEW

**Comment by barmac** [comment]
Shall we rename the repo accordingly?

**Comment by MaxTru** [comment]
> Shall we rename the repo accordingly?

Yes, let's do that.

I would propose to go for 
`bpmn-io-callbacks-to-promises`. This would also require us to change https://github.com/bpmn-io/bpmn.io/blob/master/src/links/moving-to-promises.html.

cc. @nikku as tech lead => agreed?

I will perform this change seperately of this PR / create additional PR(s).

**Comment by nikku** [comment]
Agreed!

**Review by barmac — APPROVED** [review]
🚀

**Pull request merged**
